#!/bin/sh

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.emacs" "$HOME/.emacs"
ln -sf "$PWD/.vimrc" "$HOME/.vimrc"
ln -sf "$PWD/.tmux.conf" "$HOME/.tmux.conf"
ln -sf "$PWD/.config/i3/config" "$HOME/.config/i3/config"
ln -sf "$PWD/.config/i3status/config" "$HOME/.config/i3status/config"
ln -sf "$PWD/.config/mpv/mpv.conf" "$HOME/.config/mpv/mpv.conf"
ln -sf "$PWD/.config/mpv/input.conf" "$HOME/.config/mpv/input.conf"
