export PATH=$HOME/.local/bin:$HOME/.local/bin/scripts:$PATH
xrdb -merge $HOME/.config/X11/xresources
xmodmap $HOME/.config/X11/xmodmap
xbindkeys -f $HOME/.config/X11/xbindkeys 
xsetroot -gray
exec blackbox -rc $HOME/.config/blackbox/blackboxrc
# exec 9wm -border -cursor v1
