#!/bin/sh

current_window=$(xdotool getwindowfocus)
window_list=$(xdotool search --desktop 0 "" | grep -vE "629|1043")

echo $window_list > /tmp/windows
previous_window=$(grep -oP '\S+(?= '"$current_window"')' /tmp/windows)

xdotool windowactivate $previous_window
